name: Workflow Manuel - Player
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username du Player'
        required: true
        type: string
      level:
        description: 'Level du Player'
        required: true
        type: string
      class:
        description: 'Class du Player'
        required: true
        type: choice
        options:
          - jedi
          - sith
          - rebel

jobs:
  player_infos:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage des informations du Player
        run: echo "Le joueur ${{ inputs.username }} est de niveau ${{ inputs.level }} et joue un ${{ inputs.class }}."
