name: Workflow Using Checkout
on:
#  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Call
        uses: actions/checkout@v3
        
      - name: Display README2
        run: cat README2.md
