name: Using Environment Variable Workflow

on:
  push:

jobs:
  display_env:
    runs-on: ubuntu-latest
    steps:
    - name: Define Environment Variable Message
      run: echo "Ceci est une variable d'environnement" >> $MESSAGE
    - name: show Environment Variable Message
      run: echo "$MESSAGE = ${{env.MESSAGE}}"
      
