name: Using Environment Variable Workflow

on:
  push:
  
env:
  MESSAGE : "Ceci est une variable d'environnement"

jobs:
  display_env:
    runs-on: ubuntu-latest
    steps:
    - name: show Environment Variable Message
      run: echo "MESSAGE = ${{env.MESSAGE}}"
      
