name: Secret Definition Workflow

on:
  push:

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
    - name: Display Super Secret
      run: echo "La valeur de SUPER_SECRET est \"${{ secrets.SUPER_SECRET }}\"."
