name: Publish Docker Image

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3
    - name: Authentification sur Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/exo-4-4:demo
